<?php
/**
 *
 *  hook_menu()
 */
function acm_course_menu() {
	$items = array();
	$items['student/course_entity'] = array(
		'title' => 'Course Entity',
		'page callback' => 'acm_course_formget',
		'access arguments' => array('administer acm_course'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['student/course/list'] = array(
		'title' => 'Course manage list',
		'page callback' => 'course_list', 
		'access arguments' => array('administer acm_course'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/acm_course.view.list.inc',
	);
	$items['student/course/%/view'] = array(
		'title' => 'Course entity view',
		'page callback' => 'view_courselist',
		'page arguments' => array(2),
		'access arguments' => array('administer acm_course'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/acm_course.view.list.inc',
	);
	$items['student/course/update'] = array(
		'title' => 'Course entity update',
		'page callback' => 'acm_course_update',
		'access arguments' => array('administer acm_course'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/acm_course.view.list.inc'
	);
	return $items;
}
/*
*
*hook perm
*/
function acm_course_perm() {
  return array('administer acm_course');
}

function acm_course_init() {
	//drupal_add_css(drupal_get_path('module', 'acm_course') . '/css/acm_course.css');
	//drupal_add_js(drupal_get_path('module', 'acm_course') . '/js/acm_course.js'); 

}
function acm_course_formget(){
	return drupal_get_form('acm_course_form');
}
/*
 *
 * hook form()
 */
function acm_course_form($form_id) {
	$form['title'] = array(
		'#title' => t('Title'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['exam_score'] = array(
		'#title' => t('Exam Score'),
		'#type' => 'textfield', 
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['test_score'] = array(
		'#title' => t('Test Score'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>' ,     
	);
	$form['academic_departmentid'] = array(
		'#title' => t('Academic Department Id'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['code'] = array(
		'#title' => t('Code'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['description'] = array(
		'#title' => t('Description'),
		'#type' => 'textarea',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['creditpoint'] = array(
		'#title' => t('Credit Point'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['prerequisitecodes'] = array(
		'#title' => t('Prerequisite Codes'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['prerequisites'] = array(
		'#title' => t('Prerequisite Course'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['level'] = array(
		'#title' => t('Level'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['semester'] = array(
		'#title' => t('Semester'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['session'] = array(
		'#title' => t('Session'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['lecturerincharge'] = array(
		'#title' => t('Lecturer in Charge'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['numberofcas'] = array(
		'#title' => t('Number of CAS'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['caapprovalmethod'] = array(
		'#title' => t('CA Approval Method'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['maxtestmark'] = array(
		'#title' => t('Max Test Mark'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['maxexammark'] = array(
		'#title' => t('Max Exam Mark'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['programme'] = array(
		'#title' => t('Programme'),
		'#type' => 'textfield',
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$options = array('Core'=>'Core','Elective'=>'Elective','Required'=>'Required');
	$form['type'] = array(
		'#title' => t('Type'),
		'#type' => 'select',
		'#options' => $options,
		'#prefix' => '<div class="require-data">',
		'#suffix' => '</div>',     
	);
	$form['created'] = array(
		'#title' => t('Created'),
		'#type' => 'hidden',
		'#default_value' => date("Y-m-d H:i:s"),
	);
	$form['updated'] = array(
		'#title' => t('Updated'),
		'#type' => 'hidden',
		'#default_value' => date("Y-m-d H:i:s"),
	);
	$form['submit'] = array(
		'#value' => 'Submit',
		'#type' => 'submit',
		'#submit' => array('acm_course_form_submit'),
		'#prefix' => '<div class="member_submit" >',
		'#suffix' => '</div>',
	);
	return $form;
}

function acm_course_form_validate($form, &$form_state){
	/*if(empty($form_state['values']['title'])){
		form_set_error('Title',t('Title is mandatory'));
	}
	if(empty($form_state['values']['exam_score'])){
		form_set_error('Test score',t('Title is mandatory'));
	}*/
}
function acm_course_form_submit($form, &$form_state){
	$values = $form_state['values'];
	$success = drupal_write_record('acm_course',$values);
	$batch = array(
		'title' => t('Adding Course Contents'), 
		'operations' => array(), 
		'finished' => '_acm_school_create_batch_course_content_finish', // Last function to call.
		'init_message' => t('Initializing...'),
		'progress_message' => t('Fixed @current out of @total.'),
		'error_message' => t('Adding Course Contents encountered an error.'),
	);
	$batch['operations'][] = array('_acm_school_create_batch_course_content', array());
	batch_set($batch);
}
function _acm_school_create_batch_course_content(&$context) {

	$results = db_fetch_object(db_query("SELECT MAX(id) as id FROM {acm_course}"));
	module_load_include('inc', 'node', 'node.pages');
	$node = array('type' => 'course_content');
	$node_form_state = array();
	$node_form_state['values']['title'] = t('Course Introduction');
	$node_form_state['values']['field_course_ref_id'][0]['value'] = $results->id;
	$node_form_state['values']['op'] = t('Save');
	drupal_execute('course_content_node_form', $node_form_state, (object)$node);
	$nid = $node_form_state['nid'];
	$node = node_load($nid);
	$node->uid = 1;
	node_save($node);
	
	module_load_include('inc', 'node', 'node.pages');
	$node = array('type' => 'course_content');
	$node_form_state = array();
	$node_form_state['values']['title'] = t('Course Materials');
	$node_form_state['values']['field_course_ref_id'][0]['value'] = $results->id;
	$node_form_state['values']['op'] = t('Save');
	drupal_execute('course_content_node_form', $node_form_state, (object)$node);
	$nid = $node_form_state['nid'];
	$node = node_load($nid);
	$node->uid = 1;
	node_save($node);
	
	module_load_include('inc', 'node', 'node.pages');
	$node = array('type' => 'course_content');
	$node_form_state = array();
	$node_form_state['values']['title'] = t('Course Reference');
	$node_form_state['values']['field_course_ref_id'][0]['value'] = $results->id;
	$node_form_state['values']['op'] = t('Save');
	drupal_execute('course_content_node_form', $node_form_state, (object)$node);
	$nid = $node_form_state['nid'];
	$node = node_load($nid);
	$node->uid = 1;
	node_save($node);
	
	$context['finished'] = 1;

}

function _acm_school_create_batch_course_content_finish($success, $results, $operations) {
  if ($success) {
   	drupal_goto('student/course/list');
	$message = t('Course content has been created.');
  }
  else {
    $message = t('Finished with error.');
  }
  drupal_set_message($message);
}


