<?php 
/*
 * Render student application profile items 
 * hook_acm_student_application()
 */
function college_school_acm_student_application(){
  global $user;
  switch($_GET['edit']) {
  case 'app':
	  $profile = acm_school_profile_load($user->uid);
	  return drupal_get_form('acm_school_student_profile_form', (array)$profile->profile, NULL);
  }
  switch($_GET['app']) {
  case 'sponsor':
      drupal_set_title('Sponsor');
      $studentApplication = views_get_view('uni_student_application_view');
      $studentApplication->display = 'sponsor';
      break;
    case 'course':
		drupal_set_title('Course');
        $studentApplication = views_get_view('uni_student_application_view');
        $studentApplication->display = 'course';
        break;
    case 'nextofkin':
        drupal_set_title('Next of Kin');
        $studentApplication = views_get_view('uni_student_application_view');
        $studentApplication->display = 'nextofkin';
        break;
    default:
        $studentApplication = views_get_view('uni_student_application_view');
        $studentApplication->display = 'default';
        break;
  }
  return $studentApplication;
}

/*
 * hook represents a label of items that should be configured for student application
 * profile view
 * hook_acm_student_application_items()
 */ 
function college_school_acm_student_application_items(){
  $items = array();
  $items['sponsor'] = array(
    'data' => l('Sponsor Information', 'application/sponsor')
  );
  $items['course'] = array(
    'data' => l('Course Information', 'application/course')
);
  return $items;
}

/*
 * Defines the next step after admission application
 * hook_admission_application_info()
 */
function college_school_admission_application_info(){
	$application_form = array(
    'course' => array(
      'title' => 'course',
      'form_id' => 'uni_school_admission_course_form'
    ),
    'sponsor' => array(
      'title' => 'sponsor',
      'form_id' => 'uni_school_admission_sponsors_form'
    ),
    'nextofkin' => array(
      'title' => 'nextofkin',
      'form_id' => 'uni_school_admission_nextofkin_form'
    ),
    'health' => array(
      'title' => 'health',
      'form_id' => 'uni_school_admission_health_form'
    ),
  );
  return $application_form;
}

/*
 * This hook defines the setting for school admission 
 * hook_admission_settings($type)
 */
function college_school_admission_settings($type){
 if($type == 'status') {
    $settings['admission']['admission_status_form'] = drupal_get_form('uni_school_admission_settings_form');
  }
  return $settings;

}

/*
 * setting for structure of each Academic module
 * hook_school_settings()
 */
function college_school_school_settings(){
 $settings['type'] = 'configure';
  
  $settings['configure']['admission'] = array(
    'title' => t('Set admission status'),
    'callback url' => t('admin/settings/school/admission/status')
  );
  $settings['configure']['users'] = array(
    'title' => 'Configure users',
    'callback url' => 'admin/settings/school/users'
  );
  $settings['configure']['fees'] = array(
    'title' => 'Setup Fees',
    'callback url' => 'admin/settings/school/fees'
  );
  $settings['configure']['dorm'] = array(
    'title' => 'Configure dormitory allocation',
    'callback url' => 'admin/settings/school/dormitory'
  );
  $settings['configure']['faculty'] = array(
    'title' => 'Add faculty',
    'callback url' => 'admin/settings/school/faculty/add'
  );
  $settings['configure']['department'] = array(
    'title' => 'Add department',
    'callback url' => 'admin/settings/school/department/add'
  );
  $settings['configure']['grade'] = array(
    'title' => 'Configure grading system',
    'callback url' => 'admin/settings/school/grade/gradingsystem'
  );
  
  $settings['configure']['school_settings'] = drupal_get_form('uni_school_school_settings_form');
  
  return $settings;
}
/*
 * view of student application made into a school
 * hook_admission_application_list()
 */
function college_school_admission_application_list(){
 $admission_view = views_get_view('uni_admission_view');
  return $admission_view;
}
/*
 * Describe the academic level of a school
 * hook_academic_level()
 */
function college_school_academic_level(){

 return drupal_map_assoc(array(100, 200, 300, 400, 500, 600, 700));
}
/*
 * display all the faculties in a school
 * hook_faculty()
 */
function college_school_faculty(){

}
/*
 * Display all the departments in a school
 * hook_department()
 */
function college_school_department(){

}
/*
 * Display all student grade in a school
 * hook_grade()
 */
function college_school_grade(){
  $grade_view = views_get_view('uni_grade_view');
  return $grade_view;
}
/*
 * Configure faculty settings for a school
 * hook_faculty_settings()
 */
function college_school_faculty_settings($type){
$settings['type'] = 'faculty';
  $settings['faculty']['add'] = array(
    'title' => t('Add'),
    'callback url' => 'admin/settings/school/faculty/add'
  );
  $settings['faculty']['add dept'] = array(
    'title' => 'Add department',
    'callback url' => 'admin/settings/school/department/add'
  );
  $settings['faculty']['view'] = array(
    'title' => 'View faculty',
    'callback url' => 'faculty'
  );
  
  if($type == 'add') {
    $settings['faculty']['add_faculty_form'] = drupal_get_form('uni_school_faculty_form');
  }
  if($type == 'add_dept') {
    $settings['faculty']['add_dept_form'] = drupal_get_form('uni_school_faculty_dept_form');
  }
  return $settings;
}
/*
 * Configure department settings for a school
 * hook_department_settings()
 */
function college_school_department_settings($type){
	 $settings['type'] = 'department';
  $settings['dept']['add'] = array(
    'title' => t('Add'),
    'callback url' => 'admin/settings/school/department/add'
  );
  // add course to a department
  $settings['dept']['add course'] = array(
    'title' => 'Add Course',
    'callback url' => 'admin/settings/school/department/addcourse'
  );
  $settings['dept']['grade point'] = array(
    'title' => 'Set grade point',
    'callback url' => 'admin/settings/school/grade/dept_gradepoint'
  );
  
  if($type == 'add') {
    $settings['dept']['add_dept_form'] = drupal_get_form('uni_school_faculty_dept_form'); //uni_school_add_dept_form()
  }
  if($type == 'addcourse') {
    $settings['dept']['addcourse_form'] = drupal_get_form('uni_school_addcourse_form');
  }
  
  return $settings;

}
/*
 * Configure all the course setting for a school
 * hook_course_settings()
 */
function college_school_course_settings(){
 $form['#attributes'] = array('class' => 'form-horizontal');
  $form['number_of_cas'] = array(
    '#type' => 'select',
    '#title' => t('Number of CAs'),
    '#options' => array(1,2,3,4),
    '#default_value' => variable_get('number_of_cas', (int)''),
  );
  $form['ca_approval_method'] = array(
    '#type' => 'select',
    '#title' => t('CA approval method'),
    '#options' => array('Approved along with exams'),
    '#default_value' => variable_get('ca_approval_method', ''),
  );
  $form['ca_maximum_mark'] = array(
    '#type' => 'textfield',
    '#title' => t('CA maximum mark'),
    '#default_value' => variable_get('ca_maximum_mark', (int)''),
  );
  $form['exam_maximum_mark'] = array(
    '#type' => 'textfield',
    '#title' => t('Exam maximum mark'),
    '#default_value' => variable_get('exam_maximum_mark', (int)'')
  );
  return system_settings_form($form);
}
/*
 * Configure programme settings for a school
 * hook_programme_settings()
 */
function college_school_programme_settings($type){
	$settings['type'] = 'programme';
  $settings['prog']['add'] = array(
    'title' => t('Add'),
    'callback url' => 'admin/settings/school/programme/add'
  );
  if($type == 'add') {
    $settings['prog']['add_prog_form'] = drupal_get_form('uni_school_programme_form');
  }
  
  return $settings;
}
/*
 * Configure all the grade settings for a school
 * hook_grade_settings()
 */
function college_school_grade_settings($type){
$settings['type'] = 'grade';
  $settings['grade']['configure'] = array(
    'title' => t('Configure grading system'),
    'callback url' => 'admin/settings/school/grade/gradingsystem'
  );
  // set global grading point
  $settings['grade']['grade point'] = array(
    'title' => 'Set grade point',
    'callback url' => 'admin/settings/school/grade/gradepoint'
  );
  // set grading point for a specific department
  // A staff in medicine department should be able to contact the IT
  // staff (Acadaman authorized user) to set medicine department
  // grade point to 7
  $settings['grade']['department grade point'] = array(
    'title' => 'Set department grade point',
    'callback url' => 'admin/settings/school/grade/dept_gradepoint'
  );
  $settings['grade']['grade a student'] = array(
    'title' => 'Grade a student',
    'callback url' => 'admin/settings/school/grade/add'
  );
  $settings['grade']['score a student'] = array(
    'title' => 'Score a student',
    'callback url' => 'admin/settings/school/score/add'
  );
  if($type == 'gradingsystem') {
    $settings['grade']['gradingsystem_form'] = drupal_get_form('uni_school_gradingsystem_settings_form');
  }
  if($type == 'gradepoint') {
    $settings['grade']['gradepoint_form'] = drupal_get_form('uni_school_gradepoint_settings_form'); 
  }
  if($type == 'dept_gradepoint') {
    $settings['grade']['dept_gradepoint_form'] = drupal_get_form('uni_school_dept_gradepoint_settings_form');
  }
  if($type == 'add') {
    $settings['grade']['grade_form'] = drupal_get_form('uni_school_grade_form');
  }
  
  return $settings;
}
/*
 * Configured all the score settings for a school
 * hook_score_settings()
 */
function college_school_score_settings($type){
$settings['type'] = 'score';
  if($type == 'add') {
    $settings['score']['score_form'] = drupal_get_form('uni_school_score_form');
  }
  return $settings;

}
/*
 * Display fee catalog of a school
 * hook_fees_catalog()
 */
function college_school_fees_catalog(){
return array('General', 'Program Specific');
}

/*
 * Display fee catalog of a school
 * hook_setup_tasks()
 */
function college_school_setup_tasks(){
  if($_GET['step'] == 'setup') {
    $step = 'add-faculty';
    $output = drupal_get_form('uni_school_setup_faculty_form');
    variable_set('setup_step', 'faculty');
  }
  if($_GET['step'] == 'course'){
    $step = 'add-course';
    $output = drupal_get_form('uni_school_setup_course_form');
    variable_set('setup_step', 'course');
  }
  return $output;
}
